name: 'get action job id'
description: 'get action job id'
inputs:
  job-name:
    description: 'job name'
    required: true
outputs:
  jobId: 
    description: 'job-id'
  
runs:
  using: 'node16'
  main: 'index.js'
