name: 'artifact demo'
on: [workflow_dispatch, pull_request, push]

jobs:
  artifact-test:
    runs-on: ubuntu-latest
    steps:
      - run: 'pwd'
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: test-action-demo/uploadData/