name: 'get job id'
on: [push]

jobs:
  get-job-id:
    runs-on: ubuntu-latest
    name: get job id
    steps:
      - uses: actions/checkout@v2
      - uses: ayachensiyuan/get-action-job-id@main
        with:
          run-id: ${{ github.run_id }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
