name: 'get job id'
on: [push]

jobs:
  set-job-index:
    runs-on: ubuntu-latest
    name: set index
    env:
      CURRENT_JOB_ID_INDEX: 0
  get-job-id:
    runs-on: ubuntu-latest
    name: get job id1
    steps:
      - uses: actions/checkout@v2
      - uses: ayachensiyuan/get-action-job-id@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          run-id: ${{ github.run_id }}
          run-attempt: ${{ github.run_attempt }}
  get-job-id2:
    runs-on: ubuntu-latest
    name: get job id2
    steps:
      - uses: actions/checkout@v2
      - uses: ayachensiyuan/get-action-job-id@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          run-id: ${{ github.run_id }}
          run-attempt: ${{ github.run_attempt }}
