name: 'get job id'
on: [push]

jobs:
  getJobId:
    runs-on: ubuntu-latest
    name: getJobId
    steps:
      - uses: actions/checkout@v2
      - name: set id
        id: setId
        uses: ayachensiyuan/get-action-job-id@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          run-id: ${{ github.run_id }}
          run-attempt: ${{ github.run_attempt }}
      - name: get id
        run: echo "the job id is ${{ steps.setId.outputs.jobId }}"


