name: 'get job id'
on: [push]

jobs:
  get-job-id:
    runs-on: ubuntu-latest
    name: get-job-id
    steps:
      - uses: actions/checkout@v2
      - uses: ayachensiyuan/get-action-job-id@main
        id: setId
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          run-id: ${{ github.run_id }}
          run-attempt: ${{ github.run_attempt }}
      - name: get id
        run: echo ${{ steps.setId.output.job-id }}


