name: 'get job id'
on: [push]

jobs:
  getJobId:
    runs-on: ubuntu-latest
    name: getJobId
    steps:
      - uses: actions/checkout@v2
      - name: set id
        id: setId
        uses: ayachensiyuan/get-action-job-id@v1.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          job-name: getJobId
      - name: get id
        run: echo "the job id is ${{ steps.setId.outputs.jobId }}"

