name: 'get job id'
on: [push, workflow_dispatch, pull_request]

jobs:
  getJobId:
    runs-on: ubuntu-latest
    steps:
      - name: checkContext
        run: "echo ${{ toJSON(github) }}"
      # - name: Checkout
      #   uses: actions/checkout@v2
      #   with:
      #     fetch-depth: 0
      #     ref: ${{ github.head_ref }}
      #     repository: ${{ github.event.pull_request.head.repo.full_name }}

      # - name: Merge Branches
      #   run: |
      #     git config --global user.email "bot@user.noreply.github.com"
      #     git config --global user.name "bot"

      #     git remote add ${{ github.event.pull_request.base.repo.owner.login }} ${{ github.event.pull_request.base.repo.clone_url }}
      #     git fetch ${{ github.event.pull_request.base.repo.owner.login }}
      #     git merge ${{ github.event.pull_request.base.repo.owner.login }}/${{ github.event.pull_request.base.ref }}
