name: Grant action job id
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: start01
        id: step01
        uses: ayachensiyuan/grantGithubActionJobID@v1.1
      - name: start02
        run: echo "The job-id was ${{ steps.step01.outputs['job-id'] }}"
